# This file was generated by GoReleaser. DO NOT EDIT.
cask "ken" do
  version "1.6.0"

  on_macos do
    on_arm do
      sha256 "571866346fa135f95f5e052502bc89485275f04413ab6bd372b8b4ab1e4d7933"
      url "https://github.com/townsendmerino/ken/releases/download/v#{version}/ken_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0299cbf55d31862eeebaf12182b1021c7a8cabb31766e0a1730d1812e2e59093"
      url "https://github.com/townsendmerino/ken/releases/download/v#{version}/ken_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3e121572f915424d33820c0a1d81babbd9c7c12ca148775f278f28dae479756b"
      url "https://github.com/townsendmerino/ken/releases/download/v#{version}/ken_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3d045c594803330465ddb50f2d578b4d60db68ebe7bc2e1b66801b9fb89ff598"
      url "https://github.com/townsendmerino/ken/releases/download/v#{version}/ken_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ken"
  desc "Fast hybrid code search for agents — pure Go, MCP-compatible with semble"
  homepage "https://github.com/townsendmerino/ken"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ken"
  binary "ken-mcp"

  # No zap stanza required
end
