# This file was generated by GoReleaser. DO NOT EDIT.
cask "ken" do
  version "1.4.1"

  on_macos do
    on_intel do
      sha256 "7cfc77faf0acab5eef03000439fe1f94426e097af65878bc373d1dfccb4d62ab"
      url "https://github.com/townsendmerino/ken/releases/download/v#{version}/ken_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fe1aa3ecee25c5fc25b1285fa86fedb02226a4eccbe91184abca1fa5f6d53117"
      url "https://github.com/townsendmerino/ken/releases/download/v#{version}/ken_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a605d9b44f3816ce7e7c8ccf893f8847f221c86b9610afa860c00c5884dcef31"
      url "https://github.com/townsendmerino/ken/releases/download/v#{version}/ken_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8244b93c17865036f13180f4e7d6fb0164e4dfe2d1b28e8baabbc01136e074b6"
      url "https://github.com/townsendmerino/ken/releases/download/v#{version}/ken_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ken"
  desc "Fast hybrid code search for agents — pure Go, MCP-compatible with semble"
  homepage "https://github.com/townsendmerino/ken"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ken"
  binary "ken-mcp"

  # No zap stanza required

end
