# This file was generated by GoReleaser. DO NOT EDIT.
cask "ken" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "9e88ddc39ec373c853b8be58e6271207fd7c4ab2337f501148f344a53eabcf6f"
      url "https://github.com/townsendmerino/ken/releases/download/v#{version}/ken_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2c35bacab13f90380e32bdc55ceb83d758ed41f35a72fac2f64f02a0165c32fd"
      url "https://github.com/townsendmerino/ken/releases/download/v#{version}/ken_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f0873c6014194a056e7c764b08551f5ed4a8f35abc96fdacaee155ff52590aee"
      url "https://github.com/townsendmerino/ken/releases/download/v#{version}/ken_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7eb9fc55efe530188683792c1d15b23be0593352a4c7304b90816cee10c0876c"
      url "https://github.com/townsendmerino/ken/releases/download/v#{version}/ken_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ken"
  desc "Fast hybrid code search for agents — pure Go, MCP-compatible with semble"
  homepage "https://github.com/townsendmerino/ken"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ken"
  binary "ken-mcp"

  # No zap stanza required

end
